export const committee = [
  {
    person: "Richmond",
    lastName: "Sieh",
    dateJoined: "23/05/2000",
    maritalStatus: "Single",
    position: "User",
    mustard_seed: "mustard seed",
  },
  {
    person: "David",
    lastName: "Kwame",
    dateJoined: "25/08/2000",
    maritalStatus: "Single",
    position: "Secretary",
    mustard_seed: "mustard seed",
  },
  {
    person: "Adams",
    lastName: "Sah",
    dateJoined: "20/05/2001",
    maritalStatus: "Divorced",
    position: "Organist",
    mustard_seed: "mustard seed",
  },
  {
    person: "Daniel",
    lastName: "Ampadu",
    dateJoined: "23/02/2000",
    maritalStatus: "Single",
    position: "Singer",
    mustard_seed: "mustard seed",
  },
  {
    person: "Ronald",
    lastName: "Adarkwah",
    dateJoined: "21/05/2000",
    maritalStatus: "Married",
    position: "Drummer",
    mustard_seed: "mustard seed",
  },
  {
    person: "Joseph",
    lastName: "Prempeh",
    dateJoined: "10/05/2000",
    maritalStatus: "Married",
    position: "Deacon",
    mustard_seed: "mustard seed",
  },
];
